### ISSUE TITLE
Sequence report størrelse

### ISSUE THREAD

**Issue by cmkobel** [cmkobel/pipe19#5]
seq_report.html rundsendt på mail (automail) med target b3_report fylder i skrivende stund 8MB.

Jeg tror grænsen for email-vedhæftninger er omkring 25MB, så vi skal overveje en form for kompression eller lignende på længere sigt.

**Comment by marcmtk** [comment]
I commit 71581639c984c7655355556fe839f0ec7adc20fd har jeg prøvet at udskifte svg devicet med svglite for dev_report.Rmd. Det giver en filstørrelse reduktion til 4,3 MB. Men det giver også nogle visuelle bugs, så det er ikke helt klart til at merge ind i seq_report.
